apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
  # nodeSelector:
  #   tier: web


# https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes
# kubectl label nodes <your-node-name> tier=web  --- first we have give a name to node   
# kubectl get nodes --show-labels