apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "tier"
    value: "DB"
    operator: "Equal"
    effect: "NoSchedule"


    # kubectl taint nodes [name of node] tier=DB:NoSchedule