apiVersion: v1
kind: Pod
metadata:
 name: stress
spec:
 containers:
 - name: stress
   image: techworldwithsiva/stress
   imagePullPolicy: Always
  #  resources:
  #   requests:
  #     memory: "150Mi"
  #     cpu: "250m"
  #   limits:
  #     memory: "200Mi"
  #      cpu: "500m"
