apiVersion: v1
kind: Pod
metadata:
 name: stress
spec:
 containers:
 - name: stress
   image: techworldwithsiva/stress:latest
   imagePullPolicy: Always
   command: ["sleep","200"]
   resources:
    requests:
      memory: "150Mi"
      cpu: "250m"
    limits:
      memory: "200Mi"
       cpu: "500m"
