apiVersion: v1
kind: Pod
metadata:
 name: probe
spec:
 conatiners:
 - name: nginx
   image: nginx:1.14.2
   ports:
   - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5