# apiVersion: v1
# kind: Pod
# metadata:
#  name: pod-config
# spec:
#  containers:
#  - name: nginx
#    image: nginx
#    env:
#    - name: course
#      valueFrom:
#       configMapKeyRef:
#        name: test-configmap           
#        key: course
#    - name: duration
#      valueFrom:
#       configMapKeyRef:
#        name: test-configmap
#        key: duration
---
apiVersion: v1
kind: Pod
metadata:
 name: pod-config
spec:
 containers:
 - name: nginx
   image: nginx
   envFrom:
   - configMapRef:
      name: test-configmap